---
- hosts: webservers
  roles:
    - role: system/essential
    - role: system/docker
    - role: apps/nginx-proxy
# - hosts: wiki
#   roles:
#     - role: apps/dokuwiki

    # - role: apps/dokuwiki
    #   tags:
    #     - apps
    #     - dokuwiki
    # - role: apps/dnsrobocert
    #   tags:
    #     - apps
    #     - dnsrobocert