---
- hosts: wiki
  roles:
    - role: system/essential
    - role: system/docker
    - role: apps/nginx-proxy
    - role: apps/nginx-proxy-acme
    # dnsrobocert is experimental here, it's not currently working
    # - role: apps/dnsrobocert
    - role: apps/dokuwiki
- hosts: matrix
  roles:
    - role: system/essential
    - role: system/docker
    - role: apps/nginx-proxy
    - role: apps/nginx-proxy-acme
    - role: apps/synapse
# - hosts: websites
#   roles:
#     - role: system/essential
#     - role: system/docker
#     - role: apps/nginx-proxy
#     - role: apps/sftp
#       tags:
#         - sftp
