---
- hosts: webservers
  roles:
    - role: system/essential
    - role: system/docker
- hosts: wiki
  roles:
    - role: apps/nginx-proxy
      tags:
        - nginx
    - role: apps/dnsrobocert
      tags:
        - nginx
    - role: apps/dokuwiki
    # - role: apps/dokuwiki
    #   tags:
    #     - apps
    #     - dokuwiki
    # - role: apps/dnsrobocert
    #   tags:
    #     - apps
    #     - dnsrobocert