---
- hosts: webservers
  roles:
    - role: system/essential
    - role: system/docker
- hosts: wiki
  roles:
    - role: apps/nginx-proxy
      tags:
        - nginx
    # dnsrobocert is experimental here, it's not currently working
    # - role: apps/dnsrobocert
    #   tags:
    #     - nginx
    - role: apps/dokuwiki
