- name: "Wellknown facts"
  ansible.builtin.set_fact:
    wellknown_container_dir: "{{ docker_dir }}/{{ container_name }}"

- name: Create the container directory
  file:
     path: '{{ wellknown_container_dir }}'
     state: directory
     recurse: no
     mode: "770"

- name: Start {{ container_name }} docker container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}"
    state: 'started'
    restart_policy: unless-stopped
    volumes:
      - "{{ wellknown_container_dir }}:/var/schema"
    expose:
      - '8080'
    env:
      VIRTUAL_HOST: "{{ matrix_domain }}"
      LETSENCRYPT_HOST: "{{ matrix_domain }}"
      LETSENCRYPT_EMAIL: "{{ certificate_email }}"

- name: Setup wellknown server config
  template:
    src: ./templates/server.json
    dest: "{{ wellknown_container_dir }}/{{ matrix_domain }}.server.json"
    mode: "775"
  vars:
    matrix_server: '{{ inventory_hostname }}'

- name: Setup wellknown client config
  template:
    src: ./templates/client.json
    dest: "{{ wellknown_container_dir }}/{{ matrix_domain }}.client.json"
    mode: "775"
  vars:
    matrix_server: '{{ inventory_hostname }}'