- name: Install the farmer plugin
  unarchive:
    src: "https://github.com/cosmocode/dokuwiki-plugin-farmer/archive/refs/tags/2023-04-05.tar.gz"
    dest: "{{ dokuwiki_dir }}/lib/plugins"
    remote_src: yes
    creates: "{{ dokuwiki_dir }}/lib/plugins/farmer"
    owner: dokuwiki
    group: dokuwiki

- name: Rename the farmer plugin
  command: "mv {{ dokuwiki_dir }}/lib/plugins/dokuwiki-plugin-farmer-2023-04-05 {{ dokuwiki_dir }}/lib/plugins/farmer"
  args:
    creates: "{{ dokuwiki_dir }}/lib/plugins/farmer"

- name: Add animals dir
  file:
    path: "{{ dokuwiki_dir }}/animals"
    state: directory
    recurse: no
    owner: dokuwiki
    group: dokuwiki
    mode: "770"

- name: Give dokuwiki access to public dir
  file:
    path: "{{ dokuwiki_dir }}/animals"
    state: directory
    recurse: no
    owner: dokuwiki
    group: dokuwiki
    mode: "770"

- name: Setup farm.ini config
  template:
    src: ./templates/farm.ini
    dest: "{{ dokuwiki_dir }}/conf/farm.ini"
    owner: dokuwiki
    group: dokuwiki
    mode: "770"
  vars:
    farmhost: '{{ wiki_host }}'
    basedomain: '{{ wiki_host }}'
    farmdir: '/config/dokuwiki/animals/'

- name: Setup the preload.php file
  template:
    src: ./templates/preload.php
    dest: "{{ dokuwiki_dir }}/inc/preload.php"
    owner: dokuwiki
    group: dokuwiki
    mode: "770"