- name: Dokuwiki facts
  ansible.builtin.set_fact:
    dokuwiki_dir: "{{ docker_dir }}/{{ container_name }}/dokuwiki"

- name: Dokuwiki group
  group:
    name: dokuwiki
    state: present
    gid: "{{ gid }}"

- name: Dokuwiki user
  user:
    name: dokuwiki
    state: present
    uid: "{{ uid }}"
    group: dokuwiki

- name: Create the configuration directory
  file:
     path: '{{ docker_dir }}/{{ container_name }}'
     state: directory
     recurse: no
     owner: dokuwiki
     group: dokuwiki
     mode: "770"

- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
    name: "{{ container_name }}"
    image: lscr.io/linuxserver/dokuwiki:latest
    state: 'started'
    env:
      PUID: "{{ uid  }}"
      PGID: "{{ gid }}"
      TZ: "{{ timezone }}"
      VIRTUAL_HOST: "{{ wiki_host }},*.{{ wiki_host }}"
      VIRTUAL_PORT: "80"
    volumes:
      - '{{ docker_dir }}/{{ container_name }}:/config'
    exposed:
      - '80'
    restart_policy: unless-stopped

- name: Install {{ template_name }} template archive
  unarchive:
    src: https://github.com/saschaleib/dokuwiki-template-ad-hominem/archive/refs/tags/{{ template_release }}.tar.gz
    dest: "{{ dokuwiki_dir }}/lib/tpl"
    remote_src: yes
    creates: "{{ dokuwiki_dir }}/lib/tpl/dokuwiki-template-{{ template_name }}-{{ template_release }}"
    owner: dokuwiki
    group: dokuwiki

- name: Rename the {{ template_name }} template
  command: "mv {{ dokuwiki_dir }}/lib/tpl/dokuwiki-template-{{ template_name }}-{{ template_release }} {{ dokuwiki_dir }}/lib/tpl/{{ template_name }}"
  args:
    creates: "{{ dokuwiki_dir }}/lib/tpl/{{ template_name }}"

- name: Setup dokuwiki local config
  template:
    src: ./templates/local.php
    dest: "{{ dokuwiki_dir }}/conf/local.php"
    owner: dokuwiki
    group: dokuwiki
    mode: "770"
  vars:
    title: "Farmer Wiki"
    template: '{{ template_name }}'

- name: Copy dist acl config
  copy:
    src: "{{ dokuwiki_dir }}/conf/acl.auth.php.dist"
    remote_src: true
    dest: "{{ dokuwiki_dir }}/conf/acl.auth.php"
    owner: dokuwiki
    group: dokuwiki
    mode: "770"
    force: false

- name: Setup initial users file
  template:
    src: ./templates/users.auth.php
    dest: "{{ dokuwiki_dir }}/conf/users.auth.php"
    owner: dokuwiki
    group: dokuwiki
    mode: "770"
    force: false

- name: Install the farmer plugin
  unarchive:
    src: "https://github.com/cosmocode/dokuwiki-plugin-farmer/archive/refs/tags/2023-04-05.tar.gz"
    dest: "{{ dokuwiki_dir }}/lib/plugins"
    remote_src: yes
    creates: "{{ dokuwiki_dir }}/lib/plugins/farmer"
    owner: dokuwiki
    group: dokuwiki

- name: Rename the farmer plugin
  command: "mv {{ dokuwiki_dir }}/lib/plugins/dokuwiki-plugin-farmer-2023-04-05 {{ dokuwiki_dir }}/lib/plugins/farmer"
  args:
    creates: "{{ dokuwiki_dir }}/lib/plugins/farmer"

- name: Remove authad plugin
  file:
    path: "{{ dokuwiki_dir }}/lib/plugins/authad"
    state: absent

- name: Remove authldap plugin
  file:
    path: "{{ dokuwiki_dir }}/lib/plugins/authldap"
    state: absent

- name: Remove authlpdo plugin
  file:
    path: "{{ dokuwiki_dir }}/lib/plugins/authlpdo"
    state: absent

- name: Add animals dir
  file:
    path: "{{ dokuwiki_dir }}/animals"
    state: directory
    recurse: no
    owner: dokuwiki
    group: dokuwiki
    mode: "770"

- name: Give dokuwiki access to public dir
  file:
    path: "{{ dokuwiki_dir }}/animals"
    state: directory
    recurse: no
    owner: dokuwiki
    group: dokuwiki
    mode: "770"

- name: Setup farm.ini config
  template:
    src: ./templates/farm.ini
    dest: "{{ dokuwiki_dir }}/conf/farm.ini"
    owner: dokuwiki
    group: dokuwiki
    mode: "770"
  vars:
    farmhost: '{{ wiki_host }}'
    basedomain: '{{ wiki_host }}'
    farmdir: '/config/dokuwiki/animals/'