acme:
  email_account: admin@merri-bek.tech
profiles:
- name: digitalocean
  provider: digitalocean
  provider_options:
    auth_token: "{{ auth_token }}"
certificates:
- domains:
  - wiki.merri-bek.tech
  - "*.wiki.merri-bek.tech"
  profile: digitalocean
  autocmd:
  - cmd: [/usr/local/bin/deploy_certificates.sh, -v]
    containers:
    - nginx-proxy