---
- name: Ensure dnsrobocert config directory
  file:
    path: /etc/dnsrobocert
    state: directory
    recurse: no
    mode: "770"

- name: Setup dnsrobocert configuration file
  template:
    src: ./templates/config.yml
    dest: /etc/dnsrobocert/config.yml
    mode: "770"
  register: dnsrobocert_config
  vars:
    auth_token: "{{ lookup('env','DO_PAT') }}"

# This container mounts the docker.sock so that it can execute the certificate script
# on the main nginx-proxy container
- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
    name: "{{ container_name }}"
    image: adferrand/dnsrobocert
    state: 'started'
    restart: "{{ dnsrobocert_config.changed | default(false) }}"
    restart_policy: unless-stopped
    volumes:
      - "/etc/dnsrobocert/config.yml:/etc/dnsrobocert/config.yml"
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro