- name: Update packages
  apt:
    update_cache: true
    upgrade: "yes"

- name: Auto-remove old packages
  apt:
    autoremove: true

- name: Disable SSH password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Set timezone
  lineinfile:
    path: /etc/timezone
    regexp: "^(.*)"
    line: "{{ timezone }}"
  when: timezone is defined

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists
