---
- name: "Synapse facts"
  ansible.builtin.set_fact:
    synapse_container_dir: "{{ docker_dir }}/{{ container_name }}"
    synapse_config_dir: "{{ docker_dir }}/{{ container_name }}/config"
    synapse_data_dir: "{{ docker_dir }}/{{ container_name }}/data"

- name: Create the container directory
  file:
     path: '{{ synapse_container_dir }}'
     state: directory
     recurse: no
     mode: "770"

- name: Create the config directory
  file:
    path: '{{ synapse_config_dir }}'
    state: directory
    recurse: no
    mode: "750"
    owner: "{{ synapse_uid }}"
    group: "{{ synapse_gid }}"

- name: Create the data directory
  file:
    path: '{{ synapse_data_dir }}'
    state: directory
    recurse: no
    mode: "750"
    owner: "{{ synapse_uid }}"
    group: "{{ synapse_gid }}"

- name: Ensure Synapse Docker image is pulled
  community.docker.docker_image:
    name: "{{ synapse_docker_image }}"
    source: "pull"
  register: result
  retries: "{{ default_command_retries }}"
  until: result is not failed

- name: Generate initial Synapse config and signing key
  ansible.builtin.command:
    cmd: |
      docker run
      --rm
      --name=synapse-config
      --user={{ synapse_uid }}:{{ synapse_gid }}
      --cap-drop=ALL
      --mount type=bind,src={{ synapse_config_dir }},dst=/config
      --mount type=bind,src={{ synapse_data_dir }},dst=/data
      -e SYNAPSE_SERVER_NAME={{ matrix_domain }}
      -e SYNAPSE_REPORT_STATS=no
      -e SYNAPSE_CONFIG_DIR=/config
      -e SYNAPSE_DATA_DIR=/data
      {{ synapse_docker_image }}
      generate
    creates: "{{ synapse_config_dir }}/{{ matrix_domain }}.signing.key"

- name: Setup Synapse config from template
  template:
    src: ./templates/homeserver.yaml
    dest: "{{ synapse_config_dir }}/homeserver.yaml"
    mode: "644"
    owner: "{{ synapse_uid }}"
    group: "{{ synapse_gid }}"

- name: Run Synapse container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ synapse_docker_image }}"
    state: 'started'
    restart_policy: unless-stopped
    volumes:
      - "{{ synapse_data_dir }}:/data"
      - "{{ synapse_config_dir }}:/config"
    expose:
      - '8008'
    env:
      SYNAPSE_CONFIG_DIR: "/config"
      SYNAPSE_DATA_DIR: "/data"
      UID: '{{ synapse_uid | int }}'
      GID: '{{ synapse_gid | int }}'
      TZ: "{{ timezone }}"
      VIRTUAL_HOST: "{{ inventory_hostname }}"
      LETSENCRYPT_HOST: "{{ inventory_hostname }}"
      LETSENCRYPT_EMAIL: "{{ certificate_email }}"
      VIRTUAL_PORT: "8008"

- name: Create initial admin user
  ansible.builtin.shell:
    cmd: >
      (docker exec
      -it {{ container_name }} register_new_matrix_user
      http://localhost:8008
      --config /config/homeserver.yaml
      --user {{ synapse_initial_admin_user }}
      --password {{ synapse_initial_admin_user }}
      --admin)
      >> {{ synapse_config_dir }}/initial-admin-user.txt
    creates: "{{ synapse_config_dir }}/initial-admin-user.txt"