---
- name: Create the data directory
  file:
     path: '{{ docker_dir }}/{{ container_name }}'
     state: directory
     recurse: no
     mode: "770"

- name: "{{ container_name }} facts"
  ansible.builtin.set_fact:
    container_dir: "{{ docker_dir }}/{{ container_name }}"
    letsencrypt_dir: "/etc/letsencrypt"

- name: Create the certificate script
  template:
    src: ./templates/deploy_certificates.sh
    dest: '/usr/local/bin/deploy_certificates.sh'
    mode: "770"

- name: Make sure the {{ container_name }} container is created and is running
  docker_container:
    name: "{{ container_name }}"
    image: nginxproxy/nginx-proxy
    state: 'started'
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "{{ container_dir }}/certs:/etc/nginx/certs"
      - "{{ container_dir }}/vhost:/etc/nginx/vhost.d"
      - "{{ container_dir }}/html:/usr/share/nginx/html"
      - "/usr/local/bin/deploy_certificates.sh:/usr/local/bin/deploy_certificates.sh:ro"
      - "{{ letsencrypt_dir }}/live:/etc/letsencrypt/live:ro"
      - "{{ letsencrypt_dir }}/archive:/etc/letsencrypt/archive:ro"
    ports:
      - '80:80'
      - '443:443'
    env:
      DEFAULT_ROOT: "302 /wiki/"

- include_tasks: acme.yml